version: '3'
services:
  percona-event:
     image: percona:8.0
     ports:
       - 3307:3306
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=event
  event-container:
     build: .
     ports:
       - 8064:8064
     depends_on:
      - "percona-event"             
