apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  labels:
    kind: cahce
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest        