apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: event-replicaset
  labels:
    kind: backend
spec:
  selector:
    matchLabels:
      app: event
  replicas: 3
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: event
        image: fagneto/event-repo:1.4.0
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://database:3306/event?serverTimezone=UTC&createDatabaseIfNotExist=true
        - name: spring.redis.host
          value: "redisservice"
        - name: spring.data.redis.host
          value: "redisservice"
        - name: spring.data.redis.port
          value: "6379"
        - name: spring.redis.port
          value: "6379"     
      imagePullSecrets:
      - name: eventcred